const assert = require('node:assert/strict');
const Todo = require('./logic');
const now = new Date(2026, 8, 10, 10, 0).getTime();
const legacy = {id: 'one', title: '报告', note: '保留旧备注', priority: 1, done: false, due: now + 3600000, recurrence: 'none'};
const saved = {schemaVersion: 1, items: [legacy]}, before = JSON.stringify(saved);
const migrated = Todo.readState(saved), item = migrated.items[0];
assert.equal(JSON.stringify(saved), before, 'migration must not mutate the old document');
assert.equal(item.id, legacy.id); assert.equal(item.due, legacy.due); assert.equal(item.deadline, null);
assert.deepEqual(Todo.reminders(migrated.items), Todo.reminders(saved.items));
assert.deepEqual(Todo.readState(migrated), migrated);
assert.throws(() => Todo.readState({schemaVersion: 99, items: []}));
assert.throws(() => Todo.readState({schemaVersion: 1, items: [null]}));
assert.ok(Todo.visible(item, 'today', now));
assert.ok(!Todo.overdue({...item, due: now - 1000}, now), 'past reminders are not missed deadlines');
const late = {...item, id: 'late', due: null, deadline: '2026-09-09'};
assert.ok(Todo.overdue(late, now)); assert.ok(Todo.visible(late, 'today', now));
assert.ok(!Todo.overdue({...late, deadline: '2026-09-10'}, now), 'today stays due all day');
assert.ok(Todo.visible({...item, deadline: '2026-09-17'}, 'upcoming', now));
assert.ok(!Todo.visible({...item, deadline: '2026-09-18'}, 'upcoming', now));
assert.ok(Todo.visible({...item, listId: 'work'}, 'list:work', now));
assert.ok(!Todo.visible({...item, listId: 'work'}, 'inbox', now));
assert.ok(!Todo.visible({...item, done: true}, 'today', now));
assert.equal(Todo.select([item, late], 'all', '旧备注', 'smart', now).length, 2);
assert.equal(Todo.select([item, late], 'all', '', 'smart', now)[0].id, 'late');
assert.equal(Todo.select([item, {...late, priority: 2}], 'all', '', 'priority', now)[0].id, 'late');
assert.deepEqual(Todo.reminders([{...item, done: true}]), []);
assert.deepEqual(Todo.reminders([{...item, due: null}]), []);
const repeated = {...item, due: now - 3600000, recurrence: 'daily'};
assert.equal(new Date(Todo.nextDue(repeated, now)).getHours(), 9);
assert.equal(Todo.dayKey(Todo.nextDue(repeated, now)), '2026-09-11');
const weekly = {...repeated, recurrence: 'weekly'};
assert.equal(new Date(Todo.nextDue(weekly, now)).getDay(), new Date(weekly.due).getDay());
assert.ok(Todo.nextDue(weekly, now) > now);
assert.equal(Todo.validDay('2026-02-30'), false); assert.equal(Todo.validDay('2028-02-29'), true);
assert.throws(() => Todo.validate([item, item]));
assert.throws(() => Todo.validate([{...item, due: NaN}]));
assert.throws(() => Todo.validate([{...item, priority: 5}]));
assert.throws(() => Todo.validate([{...item, note: '汉'.repeat(1400)}]));
assert.throws(() => Todo.validateState({...migrated, items: [{...item, deadline: '2026-02-30'}]}));
assert.throws(() => Todo.validateState({...migrated, items: [{...item, listId: 'missing'}]}));
assert.throws(() => Todo.validateState({...migrated, lists: [{id: 'a', name: '工作'}, {id: 'b', name: ' 工作 '}]}));
assert.throws(() => Todo.validate(Array.from({length: 51}, (_, index) => ({...legacy, id: 't' + index}))));
assert.equal(Todo.validate(Array.from({length: 1000}, (_, index) => ({...legacy, id: 't' + index, due: null}))).length, 1000);
console.log('Todo: legacy migration, independent dates/reminders, views, sorting, recurrence, cancellation and data limits passed.');
